### ISSUE TITLE
Change title, authors,etc.

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#16]

**Comment by kravcak** [comment]
@mvala 
Hi,
After I changed tex file, I did following to push it on github. But now I can't see any changes in github.
What did I do wrong?

Adela

[kravcak@ufv139-44 Phi_pol_PbPb_LHC10h]$ git status
On branch issue_16
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ALICE_analysis_note.tex

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	ALICE_analysis_note.dvi

no changes added to commit (use "git add" and/or "git commit -a")
[kravcak@ufv139-44 Phi_pol_PbPb_LHC10h]$ git add ALICE_analysis_note.tex 
[kravcak@ufv139-44 Phi_pol_PbPb_LHC10h]$ git commit -m "Title and authors added"
[issue_16 4116527] Title and authors added
 1 file changed, 1 insertion(+)
[kravcak@ufv139-44 Phi_pol_PbPb_LHC10h]$ git push origin issue_16 
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (15/15), 1.44 KiB | 0 bytes/s, done.
Total 15 (delta 9), reused 0 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 3 local objects.
To git@github.com:mvala/alice-rsn-analysis.git
 * [new branch]      issue_16 -> issue_16

**Comment by mvala** [comment]
super. You can also put in to  ```.gitignore```  
```
*.dvi
```
and it will ignore ```*.dvi``` files

After that commit with ```.gitignore``` do pull request and i will test it
