### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by zrescako** [mvala/alice-rsn-analysis#28]
Ahoj Mato,

pozerala som nejake makra, tie v /macros/analysis mi funguju aj som menila intervaly a tak. Len neviem, co to znamena, ked jefit modrou alebo cervenou farbou.
Pozrela som aj makra v /tasks/, konkretne makro AliRsnTaskCosThetaTest.cxx, nerozumiem veciam ako Helicity frame, Adair frame a preco sme pocitali lorentzove vektory. Neviem nakolko je to dolezite.
Este som chcela pripomenut tie clanky o polarizacii aby som aspon teorii rozumela.
V stredu som nemohla pocuvat meeting, lebo som bola bez internetu, ale pozerala som prezentacie a nejaki indovia tiez riesili produkciu phi. @mvala

**Comment by mvala** [comment]
Ahoj,
modry fit - dobry fit, cerveny - zly fit.

AliRsnTaskCosThetaTest je len na testovanie. Ohladom tych frame sa zajtra porozpravame
