### ISSUE TITLE
LF_pp_MC LHC15g3a3 (pp@13TeV)

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#31]

**Comment by mvala** [comment]
Train has finished. More info LF_pp_MC#594

**Comment by mvala** [comment]
Problem with merging. Train will run again

**Comment by mvala** [comment]
LF_PP_MC#598 was done

**Comment by mvala** [comment]
train : LF_pp_MC#597 . We need to check status of it

**Comment by zrescako** [comment]
https://alimonitor.cern.ch/catalogue/?path=/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp_MC/597_20170313-1053#/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp_MC/597_20170313-1053/merge_runlist_3/Stage_1/002

**Comment by mvala** [comment]
Do we have to merge it?

**Comment by mvala** [comment]
Final File is : 
```
root://alieos.saske.sk//eos/alike.saske.sk/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp_MC/597_20170313-1053/merge_runlist_3/Stage_1/002/AnalysisResults.root
```
But there is only 20x10^6 events

**Comment by zrescako** [comment]
his reply:

sorry for the late reply.
It seems there is an output there available:
https://alimonitor.cern.ch/catalogue/?path=/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp_MC/597_20170313-1053#/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp_MC/597_20170313-1053/merge_runlist_3/Stage_1/002
Could you check if the statistics is comparable to what you expect?
I’m also preparing a mail to the train operators mailing list asking for a
clarification, but I would first have an answer to the question that I give 
to you before send it.

**Comment by mvala** [comment]
So there is not full statistics

**Comment by zrescako** [comment]
ok i'm going to write them

**Comment by zrescako** [comment]
He's asking:
sorry, how far is the statistics with respect to what you do expect?
Are we at 50% of the available statistics? We have to consider the 
running inefficiency and merging that is unavoidable. 
Please, let me know.

**Comment by mvala** [comment]
We expected around 47 mil

**Comment by zrescako** [comment]
One very last question.
Is this 20 M events considered before the physics selection?

**Comment by mvala** [comment]
I think it is after physics selection. Both numbers are after phys.sell

**Comment by mvala** [comment]
LF_pp_MC#619

**Comment by mvala** [comment]
```
root://alieos.saske.sk//eos/alike.saske.sk/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp_MC/619_20170330-1043/merge_runlist_3/AnalysisResults.root
````
