### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zrescako** [mvala/alice-rsn-analysis#38]
I have a problem with rsn-config-example.json
It's running without error and I get rsn-config-example-results.root but when I want to see results in TBrowser there's nothing, no histograms.

**Comment by mvala** [comment]
i usually do stupid error. Aren't you looking in mc or data? If it is empty please copy it to eos

```
xrdcp <file> root://alieos.saske.sk//eos/alike.saske.sk/scratch/zrescako/<file>
```
