### ISSUE TITLE
ALICE meeting 20.3.2017

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#39]
https://indico.cern.ch/event/624446
Please prepare few slides about train we were running and explain problems with them. You can also say plan for next week. 
1. merge MC for pp@13TeV
2. Fix config for data pp@2.76TeV
3. Testing train for PbPb for AOD case. ESD is working localy

Please write to Kralik to give you slot in indico

**Comment by zrescako** [comment]
ok, I try and I will send you first version today

**Comment by zrescako** [comment]
there's my first version of presentation:

`root://alieos.saske.sk//eos/alike.saske.sk/scratch/zrescako/Status_of_phi.phd`

It's enogh or I should add something else? Some histograms or theory.....

**Comment by mvala** [comment]
Ok. That is enough for this week
