### ISSUE TITLE
cos(theta) of phi in Jackson frame

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#4]
```
root://alieos.saske.sk//eos/alike.saske.sk/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp/389_20160307-1141/merge_runlist_4/AnalysisResults.root
```

pt -1.0,1.0 with step as it is
phippData_100_phi_Unlike - phippData_100_phi_Mixing

**Comment by mvala** [comment]
Please do ```git pull```, because i fixed something now

**Comment by kravcak** [comment]
attached you can find c1.pdf - old results,
c1_new.pdf - recalculated yesterday
[c1.pdf](https://github.com/mvala/alice-rsn-analysis/files/175860/c1.pdf)
[c1_new.pdf](https://github.com/mvala/alice-rsn-analysis/files/175861/c1_new.pdf)

**Comment by mvala** [comment]
You can do ```git pull```

**Comment by kravcak** [comment]
Attached you can find my results / RAW cos theta spectra in Transversity frame.  



[transversity.pdf](https://github.com/mvala/alice-rsn-analysis/files/199448/transversity.pdf)
[data_transv.txt](https://github.com/mvala/alice-rsn-analysis/files/199452/data_transv.txt)

**Comment by mvala** [comment]
Efficiency?
