### ISSUE TITLE
ALICE meeting KE 2.4.2017 

### ISSUE THREAD

**Issue by zrescako** [mvala/alice-rsn-analysis#41]
- [x] train status
- [x] preparing for PbPb
- [ ] Raw spectra multiplicity vs. cosThetaJackson (one canvas with many histograms with different multiplicity)

**Comment by mvala** [comment]
I added checkboxes to description so you can mark them as done when ready

**Comment by mvala** [comment]
I added one more point. If you will be able to create canvas with RawBC of cosThetaJackson distribution for different multiplicity. I would be nice. More info #42

**Comment by mvala** [comment]
With latest version from master you should get efficiency and correction to efficiency. Without correction on number of events
