### ISSUE TITLE
path to histograms

### ISSUE THREAD

**Issue by zrescako** [mvala/alice-rsn-analysis#42]

**Comment by mvala** [comment]
With latest version there will be file <configfile>-results-final.root. In my example RsnOut-results-final.root

Here is example.
```
[mvala@vala tmp]$ root RsnOut-results-final.root
root [0] 
Attaching file RsnOut-results-final.root as _file0...
(TFile *) 0x561f9d4ad190
root [1] .ls
TFile**		RsnOut-results-final.root	
 TFile*		RsnOut-results-final.root	
  KEY: TFolder	test;1	test
root [2] test->FindFullPathName("hRawBC")
(const char *) "mgr/results/LHC15f-LHC15g3a3/pt/spectra/norm[1.10,1.15]/fit_0[0.997,1.050]/hRawBC"
root [3] h = (TH1D*)test->FindObject("mgr/results/LHC15f-LHC15g3a3/pt/spectra/norm[1.10,1.15]/fit_0[0.997,1.050]/hRawBC")
(TH1D *) 0x561f9e4a1680
root [4] h->Print("all")
TH1.Print Name  = hRawBC, Entries= 9734, Total sum= 164663
 fSumw[0]=0, x=0.75, error=0
 fSumw[1]=83416.2, x=1.25, error=910.347
 fSumw[2]=81246.8, x=1.75, error=1398.76
 fSumw[3]=0, x=2.25, error=0
root [5] 
```
So in your macro you will do
```
[mvala@vala tmp]$ cat macro.C 
void macro() {
    TFile *f = TFile::Open("RsnOut-results-final.root","READ");
    if (!f) return;

    TFolder *root = (TFolder*) f->Get("test");
    TH1D* h = (TH1D*)root->FindObject("mgr/results/LHC15f-LHC15g3a3/pt/spectra/norm[1.10,1.15]/fit_0[0.997,1.050]/hRawBC");
    h->Draw();
  }
```

**Comment by mvala** [comment]
Did you try it? Is it working for you? if yes please close issue and please add some comments

**Comment by zrescako** [comment]
it isn't working....i think it would be some stupid mistake...
error:
`Error in <HandleInterpreterException>: Trying to dereference null pointer or trying to call routine taking non-null arguments.
Execution of your code was aborted.
In file included from input_line_13:1:
/home/zrescako/git/alice/alice-rsn-analysis/macros/analysis/macro.C:6:22: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
    TH1D* h = (TH1D*)root->FindObject("mgr/results/LHC15f-LHC15g3a3/ctj_vs_mult/spectra/mult[-0.50,9.50]/norm[1.10,1.15]/fit_0[0.997,1.050]/hRawBC");
                     ^~~~
`

**Comment by mvala** [comment]
```root``` should point to ```test``` (TFolder) which is in file

**Comment by mvala** [comment]
I think this is fixed
