### ISSUE TITLE
cos(theta) of phi in Transfersity frame

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#5]

**Comment by vrlakova** [comment]
ahoj, Mato, 
este predtym, nez by som zacala robit cos theta som znovu - po git pull spustila RsnShow.C na os pt, a znovu to bolo zle - vid toto 
**********************************************
root 'RsnShow.C(1,16,20)'
************************************************
chi^2 = 1.553955
nsig = 75450.033058 +/- 7414087.124716
nbkg = 204979.202037 +/- 9253151.131359
mean = 1.019440e+00 +/- 1.881329e-02
width = 5.965914e-03 +/- 1.194583e+00
sigma = 1.000000e-03 +/- 0.000000e+00
c0 = 9.999998e-01 +/- 1.547533e+04
c1 = -3.173309e-01 +/- 1.207490e+03
c2 = -1.000000e-01 +/- 0.000000e+00
***************************************************
 a este, je pekne, ze do obrazku hore vypisuje interval, pre pt to bolo OK, ale ked som robila 

root 'RsnShow.C(3,1,1)' je interval na obrazku -1.00, -0.90  ok
ale pre root 'RsnShow.C(3,2,2)'  je to -0.90,-0.81
               root 'RsnShow.C(3,3,3)' je -0.81,-0.71
Teraz idem ucit do 9;30,
J.

**Comment by vrlakova** [comment]
My result - Jackson frame, cos theta, RAW spectra, in attached files graph2.pdf and data.txt (calculated on Sunday, March 20)
[graph2.pdf](https://github.com/mvala/alice-rsn-analysis/files/187678/graph2.pdf)
[data.txt](https://github.com/mvala/alice-rsn-analysis/files/187680/data.txt)


J.

**Comment by vrlakova** [comment]
Omylom som dala "close". 
Tak som potom dala "reopen" :)

**Comment by mvala** [comment]
When y axis would start fom 0, it would be flat, which is good. Are calculatim efficiency now?

**Comment by mvala** [comment]
Efficiency?
