### ISSUE TITLE
Download few sample LHC10h data to alieos

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#8]
```
/alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160 (100 files)
/alice/data/2010/LHC10h/000137162/ESDs/pass2/AOD160 (100 files)
```

**Comment by vrlakova** [comment]
Ahoj Mato,
chcela som stiahnut data:
/alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160,
tak som urobila find  na data, 

aliensh:[alice] [1] /alice/cern.ch/user/v/vrlakova/ >find /alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160/ AliAOD.root > LHC10h_137161.txt

vyrobila list, vybrala prvych 10, ma nasledovny format:

/alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160/0001/AliAOD.root   
/alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160/0002/AliAOD.root   
.....


a potom som pustila script: ( na ui-)
./alice_cp.sh LHC10h_137161_10.txt
ale hlasi chybu:

Host     :  pcapiserv03.cern.ch
Port     :  0
Port2    :  10000
User     :  vrlakova
Pwd      :  lTC7UfazDM9Vqu68Gl8brg
Nonce    : "  74 102 93 84 66 121 103 126 0 0 198 0 0 0 0 155 "
SID      :  7058
Encr.Rep.:  0
Expires  : Wed Apr 20 09:14:28 2016
Token is still valid!
Downloading '/eos/alike.saske.sk/alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160/0001/AliAOD.rootroot_archive.zip' ...
error: (alien_cp) cannot access source: ///alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160/0001/AliAOD.rootroot_archive.zip
Downloading '/eos/alike.saske.sk/alice/data/2010/LHC10h/000137161/ESDs/pass2/AOD160/0002/AliAOD.rootroot_archive.zip' ...

mam zle list urobeny alebo nejaky parameter, preco cita ako "AliAOD.rootroot" .?

J.

**Comment by mvala** [comment]
Opravil som chybu. urob nasledovne
```
git pull
./alice_cp.sh <meno_suboru>.txt root_archive.zip AliAOD.root
```

**Comment by vrlakova** [comment]
stiahla som po 10 suborov z kazdeho adresara, ale celkom hore je, ze po 100 suborov mam stiahnut?

**Comment by mvala** [comment]
Nemusis. Ale prosim stiahni aj esd bo prave mi pisali ze oni to testovali na esd

**Comment by vrlakova** [comment]
stiahnute esd, po 10 suborov
